[package]
name = "gui-slint"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
git-hack = { workspace = true }

slint = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"